name: Deploy to Production

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.docsearch/**'
      - 'README.md'
      - '.gitpod.yml'
  workflow_dispatch:

env:
  NO_INDEX: true
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: cache-npm-packages
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        run: npm install
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: build
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Run Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm run build

  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
      - run: npm install
      - run: npm run build
      - run: gsutil -m rsync -R -d . ${{ secrets.GCS_BUCKET }}

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
      - run: npm install
      - run: npm run build
      - run: gsutil -m rsync -R -d . ${{ secrets.GCS_PROD_BUCKET }}
